CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

\c api_pessoas

CREATE USER user_pessoa;
ALTER USER user_pessoa WITH PASSWORD '1122';
GRANT ALL PRIVILEGES ON DATABASE api_pessoas TO user_pessoa;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_pessoa;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO user_pessoa;
GRANT ALL ON SCHEMA public TO user_pessoa;
